# Generated by Django 5.1.1 on 2024-10-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='', upload_to='AccountImages/'),
        ),
    ]
