# Generated by Django 5.1.1 on 2024-10-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='Parts/_NotFound.png', upload_to='AccountImages/'),
        ),
    ]
