# Generated by Django 5.1.1 on 2024-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cart',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
