# Generated by Django 5.1.1 on 2024-10-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cart',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='AccountImages/Guest', upload_to='AccountImages/'),
        ),
    ]
