# Generated by Django 5.1.2 on 2024-11-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_account_cart_alter_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default="<class 'django.contrib.auth.models.User'>", max_length=100, null=True),
        ),
    ]
