# Generated by Django 5.1.2 on 2024-11-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='?', max_length=100, null=True),
        ),
    ]
